# Generated by Django 2.0.3 on 2018-08-27 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0002_auto_20180825_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='number',
            field=models.IntegerField(default=1),
        ),
    ]
